baseURL: "https://perscom.blackelement.studio"
languageCode: "en-us"
title: "PERSCOM"
theme: "terminal"
canonifyURLs: true
enableRobotsTXT: false
removePathAccents: true

params:
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  #contentTypeName: ""
  # "orange", "blue", "red", "green", "pink":
  themeColor: "blue"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 6
  # show selector to switch language
  showLanguageSelector: true
  # set theme to full screen width
  fullWidthTheme: true
  # center theme with default width
  centerTheme: true
  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover: true
  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated: true
  # set a custom favicon (default is a `themeColor` square)
  #favicon: "blackelement.ico"
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx Updated: 2020-xx-xx: :: Author
  updatedDatePrefix: "Updated"
  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize: false
  twitter:
    # set Twitter handles for Twitter cards
    # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
    # do not include @
    creator: ""
    site: ""
  navigation:
    help: Help
languages:
  en:
    languageName: "English"
    title: "PERSCOM"
    subtitle: "U.N.S.C. Personnel Command"
    owner: ""
    keywords: ""
    copyright: "2022 © Black Element Studio"
    menuMore: "Show more"
    readMore: "Read more"
    readOtherPosts: "Read other posts"
    newerPosts: "Newer posts"
    olderPosts: "Older posts"
    missingContentMessage: "Error, page not found"
    missingBackButtonLabel: "Back to home page"

    params:
      logo:
        logoText: "PERSCOM"
        logoHomeLink: "/"

    menu:
      main:
        - identifier: "news"
          name: "News"
          url: "/news"
        - identifier: "users"
          name: "Users"
          url: "/user"
        - identifier: "units"
          name: "Units"
          url: "/unit"
        - identifier: "about"
          name: "About"
          url: "/about"